name: Deploy Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar clasp
        run: npm install -g @google/clasp

      - name: Configurar autenticação
        run: |
          echo '{
            "token": {
              "access_token": "${{ secrets.CLASP_ACCESS_TOKEN }}",
              "refresh_token": "${{ secrets.CLASP_REFRESH_TOKEN }}",
              "scope": "https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/drive",
              "token_type": "Bearer",
              "expiry_date": 9999999999999
            }
          }' > ~/.clasprc.json

      - name: Publicar Apps Script
        run: clasp push
